CONSUMER_KEY: <your consumer key>
CONSUMER_SECRET: <your consumer secret>
API_MWURI: https://wikidata.org/w/api.php
OAUTH_MWURI: https://wikidata.org/w/index.php
SECRET_KEY: <something long and secret>
